### ISSUE TITLE
Two datepickers with different IDs throw Found 2 elements with non-unique id #date-picker-control-1

### ISSUE THREAD

**Issue by igokul1973** [afialapis/reactstrap-date-picker#1]
Below see the image with the error - sorry, but have NO time to elaborate, other than to say that the ids I entered on each DatePicker are picked-up by the hidden input properly, but the visible ones are having the same #date-picker-control-1. The behaviour of the inputs is weird thereby...

![image](https://user-images.githubusercontent.com/5454915/71324756-e8d2bf80-24f3-11ea-8bd0-a552ed0f4af3.png)

**Comment by afialapis** [comment]
Just improved the `id` and `class` attributes of the rendered DOM elements. 
Also explained it [on the readme](https://github.com/afialapis/reactstrap-date-picker#deeper-customizing).
Thanks for reporting!
