### ISSUE TITLE
Disable Certain Dates

### ISSUE THREAD

**Issue by vallard** [afialapis/reactstrap-date-picker#12]
Hello, thank you for this great tool.  I've used the `minDate` and `maxDate` items in my calendar, but between the `minDate` and `maxDate` I'd like to disable a few dates.  Is there a way I could pass an array of dates to disable? Thanks for any guidance.

**Comment by afialapis** [comment]
Hi, thanks to you. Sorry, there's no way for disabling certain dates.
It is my intention to rewrite this package (hopefully in the next days/weeks) to make it, among other improvements, hooks-compatible.
I will certainly have your suggestion in mind, as it seems a quite useful thing to add to the API.
Stay tuned!
