### ISSUE TITLE
ReferenceError: Element is not defined

### ISSUE THREAD

**Issue by manentai** [afialapis/reactstrap-date-picker#19]
I am loading the DatePicker with: 

`import { DatePicker } from 'reactstrap-date-picker'`

but as soon as I do this, I get:

     1 of 1 unhandled error
    Server Error
    ReferenceError: Element is not defined
    This error happened while generating the page. Any console logs will be displayed in the terminal window.
    Call Stack
    Object.<anonymous>

    file:///home/me/you/node_modules/reactstrap-date-picker/lib/props/util.js (15:42)
    Module._compile

    node:internal/modules/cjs/loader (1101:14)
    Object.Module._extensions..js

    node:internal/modules/cjs/loader (1153:10)
    Module.load

    node:internal/modules/cjs/loader (981:32)
    Function.Module._load

    node:internal/modules/cjs/loader (822:12)
    Module.require

    node:internal/modules/cjs/loader (1005:19)
    require

    node:internal/modules/cjs/helpers (102:18)
    Object.<anonymous>

    file:///home/me/you/node_modules/reactstrap-date-picker/lib/props/globals.js (10:13)
    Module._compile

    node:internal/modules/cjs/loader (1101:14)
    Object.Module._extensions..js

    node:internal/modules/cjs/loader (1153:10)

**Comment by afialapis** [comment]
Fixed on [700f54fac9fb587031f07fcf87af4c4b26875415](https://github.com/afialapis/reactstrap-date-picker/commit/700f54fac9fb587031f07fcf87af4c4b26875415).

v 1.0.1!
