### ISSUE TITLE
Different languages

### ISSUE THREAD

**Issue by kayoshi** [afialapis/reactstrap-date-picker#2]
Hi!
Do you configurations for localization?

**Comment by afialapis** [comment]
Hi! 
No, `reactstrap-date-picker` does not handle localization. Its value is always an ISO date string, [as shown here](https://github.com/afialapis/reactstrap-date-picker#usage).
And in my opinion would be out of scope to so. And it's easy to take any dates library -you will be probably using one in your projects- and wrap `reactstrap-date-picker` `value`/`onChange` parameters.
