### ISSUE TITLE
Type is invalid when using with latest react and react strap version

### ISSUE THREAD

**Issue by haiderali22** [afialapis/reactstrap-date-picker#24]
facing same issue as https://github.com/afialapis/reactstrap-date-picker/issues/23? Using react 18.2.0 , "reactstrap": "^9.1.5 and "bootstrap": "^5.2.3"

**Comment by afialapis** [comment]
Same issue [has same answer](https://github.com/afialapis/reactstrap-date-picker/issues/23#issuecomment-1347457462). Without further detail I cannot help.
