### ISSUE TITLE
`calendarContainer` prop causes calendar to close unexpectedly

### ISSUE THREAD

**Issue by JnnyRdng** [afialapis/reactstrap-date-picker#26]
I'm using the picker in a scrolling container which causes clipping issues. [As per the docs](https://reactstrap-date-picker.afialapis.com/#calendarcontainer), I've added
 `calendarContainer={document.body}`
which solves the scrolling issue, but now clicking anywhere inside the calendar popup (e.g. clicking next/previous month) causes it to immediately close.

Have I misunderstood the usecase here or is there a fix I can use?

Any help is massively appreciated :) 

Minimal example here: https://codesandbox.io/s/flamboyant-gates-qh64mk?file=/src/App.js

**Comment by afialapis** [comment]
Thanks for reporting and the example!

Should be fixed on 1.0.11.

https://github.com/afialapis/reactstrap-date-picker/commit/68da1afd1940ae073eeb5ce9dbe9778fef7c8b82
