### ISSUE TITLE
install lib for type script

### ISSUE THREAD

**Issue by SerDImIgor** [afialapis/reactstrap-date-picker#27]
npm i --save-dev @types/reactstrap-date-picker
npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/@types%2freactstrap-date-picker - Not found
npm ERR! 404 
npm ERR! 404  '@types/reactstrap-date-picker@*' is not in this registry.
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

**Comment by afialapis** [comment]
`reactstrap-date-picker` does not support Typescript. And there's no plan for it (yet).

**Comment by SerDImIgor** [comment]
Thanks
