### ISSUE TITLE
Onchange not firing via keybard when initial value is null

### ISSUE THREAD

**Issue by enriquin** [afialapis/reactstrap-date-picker#3]
Hello,

I'm getting an extrange behavior when the initial value of the datepicker is null.
If I change the date by typing in the textbox, the onChange event is not firing.
Once I change the date using the mouse (by clicking on a specific date in the calendar popup) it works ok and the change event is launched as expected.

Is there a recommended way to initialize the date to a blank value?

Thanks

**Comment by afialapis** [comment]
Hi!

Tried initializing with `null`/`undefined`/`""`, and both in Chrome/Firefox, and behavior is always the expected.

`onChange` event is fired just when the input has a valid date string. So, for instance, if you type '01/01/2020', it'll be fired right after typing the last zero.

Could you try to post some code reproducing the error?

Thanks!

**Comment by afialapis** [comment]
Closed by inactivity
