### ISSUE TITLE
New option to not render input group

### ISSUE THREAD

**Issue by iccicci** [afialapis/reactstrap-date-picker#6]
First of all, really a good job!

Then, my request: is it possible to add an option to render only the input without the input group in order to let us add this priceless input in our composed input group?

Perfect output (at least for my purpose) would be:
```
<>
  <Input ... />
  <PopOver ... />
</>
```

**Comment by afialapis** [comment]
Thanks, and sorry for the late.

I think it can be easily and safely done. But, before, just to get a bit more context: did you face any problem nesting InputGroup?

**Comment by iccicci** [comment]
Hi, yes, the borders a<dding other InputGroupAddon(s) aren't nice as expected

**Comment by afialapis** [comment]
Done: [5a48fd915614e71707605ac7f7541ea3f1197b39](https://github.com/afialapis/reactstrap-date-picker/commit/5a48fd915614e71707605ac7f7541ea3f1197b39)

Added `customInputGroup` prop.

Thanks!
