### ISSUE TITLE
Include valid and invalid properties that add bootstrap `is-valid` and `is-invalid` classes to the group wrapper.

### ISSUE THREAD

**Issue by ceottaki** [afialapis/reactstrap-date-picker#7]
Most, if not all, form input reactstrap components, include two properties that can be used for styling form validation by using the `is-valid` and `is-invalid` classes from Bootstrap.

The DatePicker currently does not include that option.

I request that the option be included, please, and I will submit a pull request shortly to solve this issue.

**Comment by afialapis** [comment]
Done, 
Thanks for the contribution!
